### ISSUE TITLE
Add  @lastmodifiedBy @createDate please

### ISSUE THREAD

**Issue by Willjobs94** [Wikunia/brackets-FuncDocr#44]
I'm new using brackets, and I've installed funcDor cause I really love to document all of my work.
I don't know if this function really exist, but i would like to have those options.

Thanks for reading.
Feedback make us grow :)

**Comment by Wikunia** [comment]
Haha always new ideas in your head? :)

**Comment by Willjobs94** [comment]
jejejej as a mater of fact yes!!

**Comment by Willjobs94** [comment]
So what should i do ?
Open my .json and add those lines ?
Thanks for feedback

**Comment by Wikunia** [comment]
It's really easy to add new things like this using the `definitions` folder. If you think that some changes are only interesting for you, you can add yours there. Otherwise you can make a PR. I'm thinking about an option to add new stuff easily and store it safely cause at the moment every update of the extension will destroy (reset) the `definitions` file.
I changed the files to support your options as well now. You can download these changed files or simply install from url (cause this new version isn't registered yet)

**Comment by Willjobs94** [comment]
So, excuse me again for my litter experience in the field, but if I've already have the extension installed, 
Do I need to remove it and installing again, or just wait until an available update.

Thanks for feedback, and sorry for my English.

**Comment by Wikunia** [comment]
Hi no problem :)
There are several options to install/update an extension in Brackets.

You can download the zip archive on github and extract it inside the extension folder (worst way ever :D) 
You can open the extension manager and use `Install from Url` on the bottom left (using the github url) That's the best way at the moment cause I didn't register this newest version yet, cause I think I can upgrade the feature in a better way.
Otherwise you can wait until an update after I registered it (this may take some weeks for this special issue cause I have some other work to do for university... ) 
Normally I always register new versions as soon as possible ;) but this are just few simple changes so I'll wait a bit.

**Comment by Willjobs94** [comment]
OK so for the moment I'll edit the definitions file, I will also try to help you if you allow me, even as a newbie I'm very curious and fast learning.

:+1:  :D

**Comment by Wikunia** [comment]
Sure! If you have any ideas => make an issue and maybe a PR :)
I'm thinking about making the definitions file as a preference so it can be changed and won't change back after an update. Maybe on the `@lastmodifiedBy [[name]]` it should be possible to define hints for `name` and `@lastmodifiedDate [[date]]` should have a timestamp as a hint.

**Comment by Willjobs94** [comment]
Wow ! I was thinking the same by now ! and also in author add an email hint, and also when you click enter not only put an ' * ' but also ' @ ' whit the corresponding space between them in order to automatic appear the hint of all  " at options" . 
I don't know so much about working with github, but I will start working with you I hope you help me to know this environment, I will also keep study by my side.

**Comment by Wikunia** [comment]
I think the adding an extra `@` in the line isn't always the best ;) When you write a multiline Description you don't want the `@` at the beginning.

Well to learn GitHub you might want to use your `test` repo and use `branches`. Then you can fork my project and work on it. The I think easiest way is to delete the extension go into the extension folder and clone the fork there. Then you can make changes and test them directly after reloading brackets. Then you can commit the changes and make a PR.

**Comment by Willjobs94** [comment]
Ok, thanks, and you're right about the multipleline Description, also it would be nice if in the preferences pane we can have both option.
